{% set name = "session-info" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/session_info-{{ version }}.tar.gz
  sha256: d71950d5a8ce7f7f7d5e86aa208c148c4e50b5440b77d5544d422b48e4f3ed41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - stdlib-list

test:
  imports:
    - session_info
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/joelostblom/session_info
  summary: session_info outputs version information for modules loaded in the current session, Python, and the OS.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivirshup
